name: cPanel Github CI/CD

on:
  push:
    branches:
      - main

env:
  TARGET_REPO_OWNER: "DGwebdes"
  TARGET_REPO_NAME: "cp-gh-artifact"
  TARGET_BRANCH: "main"


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Check source code
            uses: actions/checkout@v6
            with:
              persist-credentials: false

          - name: Set up nodejs
            uses: actions/setup-node@v6
            with:
              node-version: '24'
              cache: npm

          - name: Install dependencies
            run: npm ci 

          - name: Build
            run: npm run build          

          - name: Set up Git
            run: |
              git config --global user.name "Github Actions Bot"
              git config --global user.email "actions@github.com"

          - name: Clone target repo
            run: |
              git clone https://github.com/${{ env.TARGET_REPO_OWNER }}/${{ env.TARGET_REPO_NAME }}.git
              cd ${{ env.TARGET_REPO_NAME }}
              git remote set-url origin https://${{ secrets.TARGET_REPO_PAT }}@github.com/${{ env.TARGET_REPO_OWNER }}/${{ env.TARGET_REPO_NAME }}.git

          - name: Copy content to target-repo
            run: |
              cp -r dist/* ${{ env.TARGET_REPO_NAME }}
              cp .cpanel.yml ${{ env.TARGET_REPO_NAME }}
              cd ${{ env.TARGET_REPO_NAME }}
              git add -A
              git status
              git commit -m 'Updating application. Workflow... flowing. (commit: ${{ github.sha }})' || echo "No changes to commit"
              git push origin ${{ env.TARGET_BRANCH }}

